[project]
name = "comfyui_extendedimageformats"
description = "Adds a custom node for saving images in webp, jpeg, avif, jxl (no metadata) and supports loading workflows from saved images"
version = "1.0.0"
license = { file = "LICENSE" }
dependencies = ["pillow-avif-plugin", "jxlpy"]

#pillow-avif-plugin`, for jxl support install `jxlpy`
[project.urls]
Repository = "https://github.com/kaanyalova/ComfyUI_ExtendedImageFormats"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kaan"
DisplayName = "ComfyUI Extended Image Formats"
Icon = ""
